title: My Awesome Blog
author: Heidi
theme: minima
email: hso2@ebnet.org
description: > # this means to ignore newlines until "baseurl:"
  I am 18.

# social links
twitter_username: Hamso1120
instagram_username: heidiso1120
github_username:  Hamso1120

show_excerpts: true # set to false to remove excerpts on the homepage
